#!/bin/bash

# Pull environment variables from Vercel to local file so it can be used by the build
npx vercel pull --environment=production --token=$VERCEL_TOKEN

# Vercel requires author commit to be team member of the project
echo "[info] updating commit author's email"
git config --global user.email "$VERCEL_EMAIL"
git config --global user.name "Github Action"
git commit --allow-empty -m "$(git log -1 --pretty=%B)"

# Move irrelevant folders to keep the build clean and optimized
EXCLUDE_DIRS="./app/~dev ./commands ./src-tauri ./supabase/migrations ./trigger"
TMP_DIR="/tmp/$(basename $PWD)"
mkdir -p $TMP_DIR
mv $EXCLUDE_DIRS $TMP_DIR
echo "[info] moved excluded folders to $TMP_DIR"

NODE_OPTIONS="--max-old-space-size=7000" SKIP_LINT=true SKIP_TYPE_CHECK=true time npx vercel build --prod

# Check if build failed and exit if it did
if [ $? -ne 0 ]; then
  echo "[error] Build failed, stopping deployment"
  exit 1
fi

if [ -n "$VERCEL_TOKEN" ]; then
  time npx vercel deploy --prod --prebuilt --token=$VERCEL_TOKEN
else
  time npx vercel deploy --prod --prebuilt
fi

if [ $? -ne 0 ]; then
  echo "[error] Deployment failed, stopping deployment"
  exit 1
fi
