#!/bin/bash

source ./scripts/_helper

check_rules_file() {
    _assert_commands_exist "opencode glow"
    RULES_FILE=${RULES_FILE:-.rules}
    opencode --model "$OPENCODE_MODEL" run << EOF | glow
We have agent rules file at $RULES_FILE which should always reflect the codebase. Please check the codebase against the rule and give me a review if is should be updated or improved.

<rules_file>
$(cat "$RULES_FILE")
</rules_file>
EOF
}

setup() {
    echo "[info] installing developer commands..."
    npm i -g opencode-ai @biomejs/biome @typescript/native-preview
}

# Check if the agent rules file is still reflecting the codebase
if [[ "$1" == "check_rules_file" ]]; then
    check_rules_file
elif [[ "$1" == "setup" ]]; then
    setup
else
    echo "[error] Invalid command: $1"
    echo "Hint: check './scripts/$(basename "$0")' to see all possible commands."
fi
